
app_shop.fn.encodeImagetoBase64=function encodeImagetoBase64(element,callback){const file=element.files[0];const reader=new FileReader();reader.onload=function readerOnload(){if(callback)callback(reader.result);};reader.readAsDataURL(file);};app_shop.fn.opinionSendInfo=function sendInfoAjax(form){if(app_shop.vars.view<3&&form.find('.opinion_products__block.--opinion').length){form.find('.opinion_products__block.--opinion').append(`<div class="opinion_send menu_messages_message">${app_shop.vars.opinion_send2}</div>`);}else if(form.parents('#opinion_order').length){form.append(`<div class="opinion_send menu_messages_message">${app_shop.vars.opinion_send}</div>`);}else{form.append(`<div class="opinion_send menu_messages_message">${app_shop.vars.opinion_send2}</div>`);}
form.addClass('--ready');};app_shop.vars.blockAjaxOpinion=false;app_shop.fn.sendOpinionsAjax=function sendOpinionsAjax(form,serializeData){if(app_shop.vars.blockAjaxOpinion)return false;form.addClass('load-content');app_shop.vars.blockAjaxOpinion=true;$.ajax({type:form.attr('method'),url:form.attr('action'),data:serializeData,dataType:'JSON',success:function successFunction(response){if(response.result.id||response.result.id===0){app_shop.fn.opinionSendInfo(form);}else if(response.errors.faultCode){Alertek.Start(response.errors.faultString);}
app_shop.vars.blockAjaxOpinion=false;form.removeClass('load-content');},error:function errorFunction(){Alertek.Start(app_shop.vars.opinion_error);app_shop.vars.blockAjaxOpinion=false;form.removeClass('load-content');},});return false;}
app_shop.run(function aggregateOpinionsAdd(){$('#opinion_products textarea[name="opinion"]').each(function opinionSendInfoEach(){if($(this).val()!==''){app_shop.fn.opinionSendInfo($(this).parents('form'));}});$('.opinion_star').on('click',function opinionStarClick(){const points=$(this).siblings('strong');const input=$(this).siblings('input');$(this).addClass('active').prevAll('a').addClass('active');$(this).nextAll('a').removeClass('active');points.text($(this).attr('title'));input.val($(this).attr('rel'));if($(this).parents('form').find('.opinions_points_picture:not(.d-block)').length){$(this).parents('form').find('.opinions_points_picture:not(.d-block)').addClass('d-block');}
return false;});$(document).on('click','#opinion_order .opinion_edit',function(){$('#opinion_order form').removeClass('--ready');$('#opinion_order .opinion_send').remove();return false;});$('#opinion_products .f-button button, #opinion_order .f-button button').on('click',function submitClick(e){e.preventDefault();const formElement=$(this).parents('form');const fileElement=formElement.find('.opinion_add_photo');console.log(fileElement,fileElement.val());const textareaElement=formElement.find('textarea[name="opinion"]');let serializeData=formElement.serialize();if(!textareaElement.val()){Alertek.Start(app_shop.vars.opinion_empty);textareaElement.focus();return false;}
if(fileElement.val()){app_shop.fn.encodeImagetoBase64(fileElement[0],function encodeImage(ev){const imageBase64=encodeURIComponent(ev.replace(/data:image\/(jpg|jpeg);base64,/,''));serializeData+=`&picture=${imageBase64}`;app_shop.fn.sendOpinionsAjax(formElement,serializeData);});}else{app_shop.fn.sendOpinionsAjax(formElement,serializeData);}
return false;});const urlFunction=window.URL||window.webkitURL;$('input[type="file"]').on('change',function validateInputFile(){const file=$(this)[0].files[0];const img=new Image();let imgwidth=0;let imgheight=0;const maxwidth=2048;const maxheight=1536;img.src=urlFunction.createObjectURL(file);img.onload=function onloadImgFunction(){imgwidth=this.width;imgheight=this.height;if(imgwidth>maxwidth||imgheight>maxheight){Alertek.Start(app_shop.vars.opinion_file_size);$(this).val('');return false;}
if(file.type!=='image/jpeg'&&file.type!=='image/jpg'){Alertek.Start(app_shop.vars.opinion_file_type);$(this).val('');return false;}
return true;};});},'all','#opinion_order');app_shop.run(function aggregateOpinionsAddRwd(){if(app_shop.vars.view<3){$('#opinion_products .opinion_send').each(function opinionSendInfoEach(){$(this).parents('form').find('.opinion_products__block.--opinion').append($(this));});}else{$('#opinion_products .opinion_send').each(function opinionSendInfoEach(){$(this).parents('form').append($(this));});}},[1,2,3,4],'#opinion_products');