export default function variables() {
  return {
    htmlEl: document.documentElement,
    body: document.body,
    overlay: document.querySelector(".overlay"),
    bottomHeader: document.querySelector(".bottom-header-custom"),
    header: document.querySelector("header"),
    nav: document.querySelector(".custom-nav"),
    navCategory: document.querySelector(".nav-category"),
    navContainer: document.querySelector(".col-3-height"),
    breadcrumbText: document.querySelector(".nav-category p"),
    logoText: document.querySelector("#logo .logo-text"),
    logoImg: document.querySelector("#logo > a > img"),
    logoContainer: document.querySelector("#logo a "),
    container: document.querySelector("#container"),
    categoriesWrapper: document.querySelector(".categories-wrapper-ul"),
    ul: document.querySelector(".ul-category"),
    liDepth1: Array.from(document.querySelectorAll(".li-depth-1")),
    collapseClick: true,
    searchBar: document.querySelector("#menu_search"),
    mobileButton: document.querySelector(".button-mobile-categories"),
    categoriesWrapperUl2: document.querySelector(".categories-wrapper-ul2"),
    menuSettings: document.querySelector("#menu_settings"),
    goBackDiv: document.querySelector(".categoriesMobileBreadcrumb"),
    iconGoBack: document.querySelector(".categoriesMobileBreadcrumb i "),
    iconSpan: document.querySelector(".categoriesMobileBreadcrumb span "),
    ulMobile: document.querySelector(".wrapper-div-ul-2"),
    bottomHeader: document.querySelector(".bottom-header-custom"),
    ulMobileInnerUl: document.querySelector(".wrapper-div-ul-2 ul"),
  };
}
